/**
 * This class is generated by jOOQ
 */
package MyDB;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in test_automation
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table test_automation.Persons
	 */
	public static final MyDB.tables.Persons PERSONS = MyDB.tables.Persons.PERSONS;
}
