/**
 * This class is generated by jOOQ
 */
package MyDB;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestAutomation extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 879091986;

	/**
	 * The singleton instance of <code>test_automation</code>
	 */
	public static final TestAutomation TEST_AUTOMATION = new TestAutomation();

	/**
	 * No further instances allowed
	 */
	private TestAutomation() {
		super("test_automation");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			MyDB.tables.Persons.PERSONS);
	}
}
