/**
 * This class is generated by jOOQ
 */
package MyDB.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Persons extends org.jooq.impl.TableImpl<MyDB.tables.records.PersonsRecord> {

	private static final long serialVersionUID = -1326722154;

	/**
	 * The singleton instance of <code>test_automation.Persons</code>
	 */
	public static final MyDB.tables.Persons PERSONS = new MyDB.tables.Persons();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<MyDB.tables.records.PersonsRecord> getRecordType() {
		return MyDB.tables.records.PersonsRecord.class;
	}

	/**
	 * The column <code>test_automation.Persons.PersonID</code>.
	 */
	public final org.jooq.TableField<MyDB.tables.records.PersonsRecord, java.lang.Integer> PERSONID = createField("PersonID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>test_automation.Persons.LastName</code>.
	 */
	public final org.jooq.TableField<MyDB.tables.records.PersonsRecord, java.lang.String> LASTNAME = createField("LastName", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>test_automation.Persons.FirstName</code>.
	 */
	public final org.jooq.TableField<MyDB.tables.records.PersonsRecord, java.lang.String> FIRSTNAME = createField("FirstName", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>test_automation.Persons.Address</code>.
	 */
	public final org.jooq.TableField<MyDB.tables.records.PersonsRecord, java.lang.String> ADDRESS = createField("Address", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>test_automation.Persons.City</code>.
	 */
	public final org.jooq.TableField<MyDB.tables.records.PersonsRecord, java.lang.String> CITY = createField("City", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>test_automation.Persons</code> table reference
	 */
	public Persons() {
		this("Persons", null);
	}

	/**
	 * Create an aliased <code>test_automation.Persons</code> table reference
	 */
	public Persons(java.lang.String alias) {
		this(alias, MyDB.tables.Persons.PERSONS);
	}

	private Persons(java.lang.String alias, org.jooq.Table<MyDB.tables.records.PersonsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Persons(java.lang.String alias, org.jooq.Table<MyDB.tables.records.PersonsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, MyDB.TestAutomation.TEST_AUTOMATION, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MyDB.tables.Persons as(java.lang.String alias) {
		return new MyDB.tables.Persons(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MyDB.tables.Persons rename(java.lang.String name) {
		return new MyDB.tables.Persons(name, null);
	}
}
