/**
 * This class is generated by jOOQ
 */
package MyDB.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonsRecord extends org.jooq.impl.TableRecordImpl<MyDB.tables.records.PersonsRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1902221807;

	/**
	 * Setter for <code>test_automation.Persons.PersonID</code>.
	 */
	public void setPersonid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>test_automation.Persons.PersonID</code>.
	 */
	public java.lang.Integer getPersonid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>test_automation.Persons.LastName</code>.
	 */
	public void setLastname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>test_automation.Persons.LastName</code>.
	 */
	public java.lang.String getLastname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>test_automation.Persons.FirstName</code>.
	 */
	public void setFirstname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>test_automation.Persons.FirstName</code>.
	 */
	public java.lang.String getFirstname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>test_automation.Persons.Address</code>.
	 */
	public void setAddress(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>test_automation.Persons.Address</code>.
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>test_automation.Persons.City</code>.
	 */
	public void setCity(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>test_automation.Persons.City</code>.
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return MyDB.tables.Persons.PERSONS.PERSONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return MyDB.tables.Persons.PERSONS.LASTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return MyDB.tables.Persons.PERSONS.FIRSTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return MyDB.tables.Persons.PERSONS.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return MyDB.tables.Persons.PERSONS.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getPersonid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLastname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFirstname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonsRecord value1(java.lang.Integer value) {
		setPersonid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonsRecord value2(java.lang.String value) {
		setLastname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonsRecord value3(java.lang.String value) {
		setFirstname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonsRecord value4(java.lang.String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonsRecord value5(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PersonsRecord
	 */
	public PersonsRecord() {
		super(MyDB.tables.Persons.PERSONS);
	}

	/**
	 * Create a detached, initialised PersonsRecord
	 */
	public PersonsRecord(java.lang.Integer personid, java.lang.String lastname, java.lang.String firstname, java.lang.String address, java.lang.String city) {
		super(MyDB.tables.Persons.PERSONS);

		setValue(0, personid);
		setValue(1, lastname);
		setValue(2, firstname);
		setValue(3, address);
		setValue(4, city);
	}
}
